//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ModelDesignFirst_L1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ModelDesignFirst_L1")]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private int IDField;
        
        private string LastNameField;
        
        private string PasswordField;
        
        private string PhoneField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Photo", Namespace="http://schemas.datacontract.org/2004/07/ModelDesignFirst_L1")]
    public partial class Photo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime CreationDateField;
        
        private string EventField;
        
        private bool FlgMovedField;
        
        private string FullPathField;
        
        private int HeightField;
        
        private int IDField;
        
        private string LocationField;
        
        private string PhotoNameField;
        
        private string TaggedPersonsField;
        
        private int WeightField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Event
        {
            get
            {
                return this.EventField;
            }
            set
            {
                this.EventField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlgMoved
        {
            get
            {
                return this.FlgMovedField;
            }
            set
            {
                this.FlgMovedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullPath
        {
            get
            {
                return this.FullPathField;
            }
            set
            {
                this.FullPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoName
        {
            get
            {
                return this.PhotoNameField;
            }
            set
            {
                this.PhotoNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaggedPersons
        {
            get
            {
                return this.TaggedPersonsField;
            }
            set
            {
                this.TaggedPersonsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Weight
        {
            get
            {
                return this.WeightField;
            }
            set
            {
                this.WeightField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movie", Namespace="http://schemas.datacontract.org/2004/07/ModelDesignFirst_L1")]
    public partial class Movie : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime CreationDateField;
        
        private int DurationField;
        
        private string EventField;
        
        private bool FlgMovedField;
        
        private string FullPathField;
        
        private int IDField;
        
        private string LocationField;
        
        private string MovieNameField;
        
        private string TaggedPersonsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duration
        {
            get
            {
                return this.DurationField;
            }
            set
            {
                this.DurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Event
        {
            get
            {
                return this.EventField;
            }
            set
            {
                this.EventField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlgMoved
        {
            get
            {
                return this.FlgMovedField;
            }
            set
            {
                this.FlgMovedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullPath
        {
            get
            {
                return this.FullPathField;
            }
            set
            {
                this.FullPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MovieName
        {
            get
            {
                return this.MovieNameField;
            }
            set
            {
                this.MovieNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaggedPersons
        {
            get
            {
                return this.TaggedPersonsField;
            }
            set
            {
                this.TaggedPersonsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyCode", Namespace="http://schemas.datacontract.org/2004/07/ModelDesignFirst_L1")]
    public partial class PropertyCode : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private int IDField;
        
        private ModelDesignFirst_L1.Property[] PropertiesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModelDesignFirst_L1.Property[] Properties
        {
            get
            {
                return this.PropertiesField;
            }
            set
            {
                this.PropertiesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Property", Namespace="http://schemas.datacontract.org/2004/07/ModelDesignFirst_L1")]
    public partial class Property : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private int IDField;
        
        private int MediaIDField;
        
        private ModelDesignFirst_L1.PropertyCode PropertyCodeField;
        
        private int PropertyCodeIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MediaID
        {
            get
            {
                return this.MediaIDField;
            }
            set
            {
                this.MediaIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModelDesignFirst_L1.PropertyCode PropertyCode
        {
            get
            {
                return this.PropertyCodeField;
            }
            set
            {
                this.PropertyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PropertyCodeID
        {
            get
            {
                return this.PropertyCodeIDField;
            }
            set
            {
                this.PropertyCodeIDField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IProject")]
public interface IProject
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceUser/CreateUser", ReplyAction="http://tempuri.org/InterfaceUser/CreateUserResponse")]
    ModelDesignFirst_L1.User CreateUser(string firstName, string lastName, string email, string password, string phone, string address);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceUser/CreateUser", ReplyAction="http://tempuri.org/InterfaceUser/CreateUserResponse")]
    System.Threading.Tasks.Task<ModelDesignFirst_L1.User> CreateUserAsync(string firstName, string lastName, string email, string password, string phone, string address);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceUser/UpdateUser", ReplyAction="http://tempuri.org/InterfaceUser/UpdateUserResponse")]
    ModelDesignFirst_L1.User UpdateUser(int id, string firstName, string lastName, string email, string password, string phone, string address);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceUser/UpdateUser", ReplyAction="http://tempuri.org/InterfaceUser/UpdateUserResponse")]
    System.Threading.Tasks.Task<ModelDesignFirst_L1.User> UpdateUserAsync(int id, string firstName, string lastName, string email, string password, string phone, string address);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceUser/DeleteUser", ReplyAction="http://tempuri.org/InterfaceUser/DeleteUserResponse")]
    bool DeleteUser(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceUser/DeleteUser", ReplyAction="http://tempuri.org/InterfaceUser/DeleteUserResponse")]
    System.Threading.Tasks.Task<bool> DeleteUserAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceUser/GetUserById", ReplyAction="http://tempuri.org/InterfaceUser/GetUserByIdResponse")]
    ModelDesignFirst_L1.User GetUserById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceUser/GetUserById", ReplyAction="http://tempuri.org/InterfaceUser/GetUserByIdResponse")]
    System.Threading.Tasks.Task<ModelDesignFirst_L1.User> GetUserByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceUser/GetAllUsers", ReplyAction="http://tempuri.org/InterfaceUser/GetAllUsersResponse")]
    ModelDesignFirst_L1.User[] GetAllUsers();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceUser/GetAllUsers", ReplyAction="http://tempuri.org/InterfaceUser/GetAllUsersResponse")]
    System.Threading.Tasks.Task<ModelDesignFirst_L1.User[]> GetAllUsersAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceUser/Login", ReplyAction="http://tempuri.org/InterfaceUser/LoginResponse")]
    bool Login(string email, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceUser/Login", ReplyAction="http://tempuri.org/InterfaceUser/LoginResponse")]
    System.Threading.Tasks.Task<bool> LoginAsync(string email, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/CreatePhoto", ReplyAction="http://tempuri.org/InterfacePhoto/CreatePhotoResponse")]
    ModelDesignFirst_L1.Photo CreatePhoto(string fullPath, string photoName, System.DateTime creationDate, string corelatedEvent, string taggedPersons, string location, int height, int weight);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/CreatePhoto", ReplyAction="http://tempuri.org/InterfacePhoto/CreatePhotoResponse")]
    System.Threading.Tasks.Task<ModelDesignFirst_L1.Photo> CreatePhotoAsync(string fullPath, string photoName, System.DateTime creationDate, string corelatedEvent, string taggedPersons, string location, int height, int weight);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/DeletePhoto", ReplyAction="http://tempuri.org/InterfacePhoto/DeletePhotoResponse")]
    bool DeletePhoto(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/DeletePhoto", ReplyAction="http://tempuri.org/InterfacePhoto/DeletePhotoResponse")]
    System.Threading.Tasks.Task<bool> DeletePhotoAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetPhotoById", ReplyAction="http://tempuri.org/InterfacePhoto/GetPhotoByIdResponse")]
    ModelDesignFirst_L1.Photo GetPhotoById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetPhotoById", ReplyAction="http://tempuri.org/InterfacePhoto/GetPhotoByIdResponse")]
    System.Threading.Tasks.Task<ModelDesignFirst_L1.Photo> GetPhotoByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetAllPhotos", ReplyAction="http://tempuri.org/InterfacePhoto/GetAllPhotosResponse")]
    ModelDesignFirst_L1.Photo[] GetAllPhotos();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetAllPhotos", ReplyAction="http://tempuri.org/InterfacePhoto/GetAllPhotosResponse")]
    System.Threading.Tasks.Task<ModelDesignFirst_L1.Photo[]> GetAllPhotosAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/UpdatePhoto", ReplyAction="http://tempuri.org/InterfacePhoto/UpdatePhotoResponse")]
    ModelDesignFirst_L1.Photo UpdatePhoto(int id, string fullPath, string PhotoName, System.DateTime creationDate, string corelatedEvent, string taggedPersons, string location, int height, int weight);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/UpdatePhoto", ReplyAction="http://tempuri.org/InterfacePhoto/UpdatePhotoResponse")]
    System.Threading.Tasks.Task<ModelDesignFirst_L1.Photo> UpdatePhotoAsync(int id, string fullPath, string PhotoName, System.DateTime creationDate, string corelatedEvent, string taggedPersons, string location, int height, int weight);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMovie/CreateMovie", ReplyAction="http://tempuri.org/InterfaceMovie/CreateMovieResponse")]
    ModelDesignFirst_L1.Movie CreateMovie(string fullPath, string movieName, System.DateTime creationDate, string corelatedEvent, string taggedPersons, string location, int duration);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMovie/CreateMovie", ReplyAction="http://tempuri.org/InterfaceMovie/CreateMovieResponse")]
    System.Threading.Tasks.Task<ModelDesignFirst_L1.Movie> CreateMovieAsync(string fullPath, string movieName, System.DateTime creationDate, string corelatedEvent, string taggedPersons, string location, int duration);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMovie/DeleteMovie", ReplyAction="http://tempuri.org/InterfaceMovie/DeleteMovieResponse")]
    bool DeleteMovie(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMovie/DeleteMovie", ReplyAction="http://tempuri.org/InterfaceMovie/DeleteMovieResponse")]
    System.Threading.Tasks.Task<bool> DeleteMovieAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMovie/GetMovieById", ReplyAction="http://tempuri.org/InterfaceMovie/GetMovieByIdResponse")]
    ModelDesignFirst_L1.Movie GetMovieById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMovie/GetMovieById", ReplyAction="http://tempuri.org/InterfaceMovie/GetMovieByIdResponse")]
    System.Threading.Tasks.Task<ModelDesignFirst_L1.Movie> GetMovieByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMovie/GetAllMovies", ReplyAction="http://tempuri.org/InterfaceMovie/GetAllMoviesResponse")]
    ModelDesignFirst_L1.Movie[] GetAllMovies();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMovie/GetAllMovies", ReplyAction="http://tempuri.org/InterfaceMovie/GetAllMoviesResponse")]
    System.Threading.Tasks.Task<ModelDesignFirst_L1.Movie[]> GetAllMoviesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMovie/UpdateMovie", ReplyAction="http://tempuri.org/InterfaceMovie/UpdateMovieResponse")]
    ModelDesignFirst_L1.Movie UpdateMovie(int id, string fullPath, string movieName, System.DateTime creationDate, string corelatedEvent, string taggedPersons, string location, int duration);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMovie/UpdateMovie", ReplyAction="http://tempuri.org/InterfaceMovie/UpdateMovieResponse")]
    System.Threading.Tasks.Task<ModelDesignFirst_L1.Movie> UpdateMovieAsync(int id, string fullPath, string movieName, System.DateTime creationDate, string corelatedEvent, string taggedPersons, string location, int duration);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePropertyCode/CreatePropertyCode", ReplyAction="http://tempuri.org/InterfacePropertyCode/CreatePropertyCodeResponse")]
    ModelDesignFirst_L1.PropertyCode CreatePropertyCode(string code);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePropertyCode/CreatePropertyCode", ReplyAction="http://tempuri.org/InterfacePropertyCode/CreatePropertyCodeResponse")]
    System.Threading.Tasks.Task<ModelDesignFirst_L1.PropertyCode> CreatePropertyCodeAsync(string code);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePropertyCode/DeletePropertyCode", ReplyAction="http://tempuri.org/InterfacePropertyCode/DeletePropertyCodeResponse")]
    bool DeletePropertyCode(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePropertyCode/DeletePropertyCode", ReplyAction="http://tempuri.org/InterfacePropertyCode/DeletePropertyCodeResponse")]
    System.Threading.Tasks.Task<bool> DeletePropertyCodeAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePropertyCode/GetPropertyCodes", ReplyAction="http://tempuri.org/InterfacePropertyCode/GetPropertyCodesResponse")]
    ModelDesignFirst_L1.PropertyCode[] GetPropertyCodes();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePropertyCode/GetPropertyCodes", ReplyAction="http://tempuri.org/InterfacePropertyCode/GetPropertyCodesResponse")]
    System.Threading.Tasks.Task<ModelDesignFirst_L1.PropertyCode[]> GetPropertyCodesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceProperty/CreateProperty", ReplyAction="http://tempuri.org/InterfaceProperty/CreatePropertyResponse")]
    ModelDesignFirst_L1.Property CreateProperty(string desc, int mediaID, int propCodeID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceProperty/CreateProperty", ReplyAction="http://tempuri.org/InterfaceProperty/CreatePropertyResponse")]
    System.Threading.Tasks.Task<ModelDesignFirst_L1.Property> CreatePropertyAsync(string desc, int mediaID, int propCodeID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceProperty/GetPropertiesByMediaID", ReplyAction="http://tempuri.org/InterfaceProperty/GetPropertiesByMediaIDResponse")]
    ModelDesignFirst_L1.Property[] GetPropertiesByMediaID(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceProperty/GetPropertiesByMediaID", ReplyAction="http://tempuri.org/InterfaceProperty/GetPropertiesByMediaIDResponse")]
    System.Threading.Tasks.Task<ModelDesignFirst_L1.Property[]> GetPropertiesByMediaIDAsync(int id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IProjectChannel : IProject, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ProjectClient : System.ServiceModel.ClientBase<IProject>, IProject
{
    
    public ProjectClient()
    {
    }
    
    public ProjectClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ProjectClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ProjectClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ProjectClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public ModelDesignFirst_L1.User CreateUser(string firstName, string lastName, string email, string password, string phone, string address)
    {
        return base.Channel.CreateUser(firstName, lastName, email, password, phone, address);
    }
    
    public System.Threading.Tasks.Task<ModelDesignFirst_L1.User> CreateUserAsync(string firstName, string lastName, string email, string password, string phone, string address)
    {
        return base.Channel.CreateUserAsync(firstName, lastName, email, password, phone, address);
    }
    
    public ModelDesignFirst_L1.User UpdateUser(int id, string firstName, string lastName, string email, string password, string phone, string address)
    {
        return base.Channel.UpdateUser(id, firstName, lastName, email, password, phone, address);
    }
    
    public System.Threading.Tasks.Task<ModelDesignFirst_L1.User> UpdateUserAsync(int id, string firstName, string lastName, string email, string password, string phone, string address)
    {
        return base.Channel.UpdateUserAsync(id, firstName, lastName, email, password, phone, address);
    }
    
    public bool DeleteUser(int id)
    {
        return base.Channel.DeleteUser(id);
    }
    
    public System.Threading.Tasks.Task<bool> DeleteUserAsync(int id)
    {
        return base.Channel.DeleteUserAsync(id);
    }
    
    public ModelDesignFirst_L1.User GetUserById(int id)
    {
        return base.Channel.GetUserById(id);
    }
    
    public System.Threading.Tasks.Task<ModelDesignFirst_L1.User> GetUserByIdAsync(int id)
    {
        return base.Channel.GetUserByIdAsync(id);
    }
    
    public ModelDesignFirst_L1.User[] GetAllUsers()
    {
        return base.Channel.GetAllUsers();
    }
    
    public System.Threading.Tasks.Task<ModelDesignFirst_L1.User[]> GetAllUsersAsync()
    {
        return base.Channel.GetAllUsersAsync();
    }
    
    public bool Login(string email, string password)
    {
        return base.Channel.Login(email, password);
    }
    
    public System.Threading.Tasks.Task<bool> LoginAsync(string email, string password)
    {
        return base.Channel.LoginAsync(email, password);
    }
    
    public ModelDesignFirst_L1.Photo CreatePhoto(string fullPath, string photoName, System.DateTime creationDate, string corelatedEvent, string taggedPersons, string location, int height, int weight)
    {
        return base.Channel.CreatePhoto(fullPath, photoName, creationDate, corelatedEvent, taggedPersons, location, height, weight);
    }
    
    public System.Threading.Tasks.Task<ModelDesignFirst_L1.Photo> CreatePhotoAsync(string fullPath, string photoName, System.DateTime creationDate, string corelatedEvent, string taggedPersons, string location, int height, int weight)
    {
        return base.Channel.CreatePhotoAsync(fullPath, photoName, creationDate, corelatedEvent, taggedPersons, location, height, weight);
    }
    
    public bool DeletePhoto(int id)
    {
        return base.Channel.DeletePhoto(id);
    }
    
    public System.Threading.Tasks.Task<bool> DeletePhotoAsync(int id)
    {
        return base.Channel.DeletePhotoAsync(id);
    }
    
    public ModelDesignFirst_L1.Photo GetPhotoById(int id)
    {
        return base.Channel.GetPhotoById(id);
    }
    
    public System.Threading.Tasks.Task<ModelDesignFirst_L1.Photo> GetPhotoByIdAsync(int id)
    {
        return base.Channel.GetPhotoByIdAsync(id);
    }
    
    public ModelDesignFirst_L1.Photo[] GetAllPhotos()
    {
        return base.Channel.GetAllPhotos();
    }
    
    public System.Threading.Tasks.Task<ModelDesignFirst_L1.Photo[]> GetAllPhotosAsync()
    {
        return base.Channel.GetAllPhotosAsync();
    }
    
    public ModelDesignFirst_L1.Photo UpdatePhoto(int id, string fullPath, string PhotoName, System.DateTime creationDate, string corelatedEvent, string taggedPersons, string location, int height, int weight)
    {
        return base.Channel.UpdatePhoto(id, fullPath, PhotoName, creationDate, corelatedEvent, taggedPersons, location, height, weight);
    }
    
    public System.Threading.Tasks.Task<ModelDesignFirst_L1.Photo> UpdatePhotoAsync(int id, string fullPath, string PhotoName, System.DateTime creationDate, string corelatedEvent, string taggedPersons, string location, int height, int weight)
    {
        return base.Channel.UpdatePhotoAsync(id, fullPath, PhotoName, creationDate, corelatedEvent, taggedPersons, location, height, weight);
    }
    
    public ModelDesignFirst_L1.Movie CreateMovie(string fullPath, string movieName, System.DateTime creationDate, string corelatedEvent, string taggedPersons, string location, int duration)
    {
        return base.Channel.CreateMovie(fullPath, movieName, creationDate, corelatedEvent, taggedPersons, location, duration);
    }
    
    public System.Threading.Tasks.Task<ModelDesignFirst_L1.Movie> CreateMovieAsync(string fullPath, string movieName, System.DateTime creationDate, string corelatedEvent, string taggedPersons, string location, int duration)
    {
        return base.Channel.CreateMovieAsync(fullPath, movieName, creationDate, corelatedEvent, taggedPersons, location, duration);
    }
    
    public bool DeleteMovie(int id)
    {
        return base.Channel.DeleteMovie(id);
    }
    
    public System.Threading.Tasks.Task<bool> DeleteMovieAsync(int id)
    {
        return base.Channel.DeleteMovieAsync(id);
    }
    
    public ModelDesignFirst_L1.Movie GetMovieById(int id)
    {
        return base.Channel.GetMovieById(id);
    }
    
    public System.Threading.Tasks.Task<ModelDesignFirst_L1.Movie> GetMovieByIdAsync(int id)
    {
        return base.Channel.GetMovieByIdAsync(id);
    }
    
    public ModelDesignFirst_L1.Movie[] GetAllMovies()
    {
        return base.Channel.GetAllMovies();
    }
    
    public System.Threading.Tasks.Task<ModelDesignFirst_L1.Movie[]> GetAllMoviesAsync()
    {
        return base.Channel.GetAllMoviesAsync();
    }
    
    public ModelDesignFirst_L1.Movie UpdateMovie(int id, string fullPath, string movieName, System.DateTime creationDate, string corelatedEvent, string taggedPersons, string location, int duration)
    {
        return base.Channel.UpdateMovie(id, fullPath, movieName, creationDate, corelatedEvent, taggedPersons, location, duration);
    }
    
    public System.Threading.Tasks.Task<ModelDesignFirst_L1.Movie> UpdateMovieAsync(int id, string fullPath, string movieName, System.DateTime creationDate, string corelatedEvent, string taggedPersons, string location, int duration)
    {
        return base.Channel.UpdateMovieAsync(id, fullPath, movieName, creationDate, corelatedEvent, taggedPersons, location, duration);
    }
    
    public ModelDesignFirst_L1.PropertyCode CreatePropertyCode(string code)
    {
        return base.Channel.CreatePropertyCode(code);
    }
    
    public System.Threading.Tasks.Task<ModelDesignFirst_L1.PropertyCode> CreatePropertyCodeAsync(string code)
    {
        return base.Channel.CreatePropertyCodeAsync(code);
    }
    
    public bool DeletePropertyCode(int id)
    {
        return base.Channel.DeletePropertyCode(id);
    }
    
    public System.Threading.Tasks.Task<bool> DeletePropertyCodeAsync(int id)
    {
        return base.Channel.DeletePropertyCodeAsync(id);
    }
    
    public ModelDesignFirst_L1.PropertyCode[] GetPropertyCodes()
    {
        return base.Channel.GetPropertyCodes();
    }
    
    public System.Threading.Tasks.Task<ModelDesignFirst_L1.PropertyCode[]> GetPropertyCodesAsync()
    {
        return base.Channel.GetPropertyCodesAsync();
    }
    
    public ModelDesignFirst_L1.Property CreateProperty(string desc, int mediaID, int propCodeID)
    {
        return base.Channel.CreateProperty(desc, mediaID, propCodeID);
    }
    
    public System.Threading.Tasks.Task<ModelDesignFirst_L1.Property> CreatePropertyAsync(string desc, int mediaID, int propCodeID)
    {
        return base.Channel.CreatePropertyAsync(desc, mediaID, propCodeID);
    }
    
    public ModelDesignFirst_L1.Property[] GetPropertiesByMediaID(int id)
    {
        return base.Channel.GetPropertiesByMediaID(id);
    }
    
    public System.Threading.Tasks.Task<ModelDesignFirst_L1.Property[]> GetPropertiesByMediaIDAsync(int id)
    {
        return base.Channel.GetPropertiesByMediaIDAsync(id);
    }
}
